const fs = require('fs-extra');
const { Sequelize } = require('sequelize');
if (fs.existsSync('set.env'))
    require('dotenv').config({ path: __dirname + '/set.env' });
const path = require("path");
const databasePath = path.join(__dirname, './database.db');
const DATABASE_URL = process.env.DATABASE_URL === undefined
    ? databasePath
    : process.env.DATABASE_URL;
module.exports = { session: process.env.SESSION_ID || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0ZocE9YeGZiTHVXYzFHNXFqbFlkK1NjazY4VmlGaDFkSmM1TDF4Z3JGdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNGl5VzlseDlTTlBaMmFudmNpejhrSHN4YVgxekdJWmxNNzEyOXluNmhIbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNSXFTN1djQkRubWMvQi9HUkJiQnVjajlxUFgzQm1WeW03VTY5dStXUTEwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHMTUrRHdyREJSOFo1WW1GdE0wZThuNFVxa3RrWXd0U2JOTGY1R3dVOGk4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNBSS9iWk4wV3Exc094dVpLMldGRnlmTnFPMFNuQjFabXJUYlRvWDJCRkU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im5MeXJEM2h3bTA1cENHamhMSFNVa1V5ajEwbHk4UlVpSjB1V2kzQ010WG89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkZjZk5iMGw1OEdlNkp6L3hmaGJHVCtRTEorTTVONEJmZWNJZnQvbm1GRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaHR5S0ovZmE0TTU3WTR4NjdpcWhJdnQwemRGV1pCYmp0MGxSQXZRZWhtYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktUZm9vT2NaeEdlZ3N0d1JjaDNvUG1lU0NiNGpRUkxackVhNnQ0M0VzS2cxUHZTMHlOdC9SYkZIYWhNUzNtb09hTllIdWpBWHZhMVZwWEZlSWs1ZkRnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODAsImFkdlNlY3JldEtleSI6IlpwQTh1TG55SFMvUW5vNEZDL0lQVEJHUHNpVEhzWGpIcjVmN0JOSUt0L0U9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzkzNzUzMzI3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjU0OTkxNzA4NjU5NjlFMkIzNjNBRDBFRDM2QzlFQjQ2In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDU1ODc3NzN9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5Mzc1MzMyN0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJERDEwQ0Y0NzI2NjBFMTQ5OEJFQTQ5RThGMjgyMkNGRiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ1NTg3Nzc0fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTM3NTMzMjdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiM0VBNTZGRjU1RTJENjlGQTk0NkI4MDQ3QjhENUUyNEIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0NTU4Nzc4Nn0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzkzNzUzMzI3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkQzNjg1MzMzNTU3QkM2RTUxNEIwMkE4NzE0QTVCNzlCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDU1ODc3OTN9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5Mzc1MzMyN0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3ODk1NzZCQkYyOTREREIxOTNGMTM0MjUzQUJDMERBQyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ1NTg3ODAyfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTM3NTMzMjdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNEE3RDVGMENBMjAyMjNEM0ZBRkExRDBCOTczQkVGOUQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0NTU4NzgwOX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzkzNzUzMzI3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6Ijc3RUI2MkVEODBDMzY2Q0E1REMzNjUwRkE5MUVCQUVCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDU1ODc4MTd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5Mzc1MzMyN0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI4NjkzNTRCREFCOTRBMTAyQTgxRDQ0OUIwNTZGMzMyRiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ1NTg3ODE5fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJKMG9aejB0d1RlS05oNWhuek1CNEl3IiwicGhvbmVJZCI6IjU4NDhjNjI3LTY0NmMtNDM5ZC1iNTc4LTZkY2I0MTNlYTgyZiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrMm9CMVlBZWhtTVlUN2k4RUNjTkpUZ2hIYTg9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ3orRnBtMDluZFlWemZQREZEZzk1cjMzNk9jPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlJTUlFIUDJFIiwibWUiOnsiaWQiOiIyNTQ3OTM3NTMzMjc6NTJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi766p2ajZgO+uqe+uqdmo2YDwnZOHbmV3dG9u766p2ajZgO+uqe+uqdmo2YAifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0lpdHJmWURFS3VjcnNBR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Iks1bXpzOFJpc1ZtWTh3WjNjNXAyUGhVNUREVG9MMnZtZFhPWnF6L09yZ1U9IiwiYWNjb3VudFNpZ25hdHVyZSI6IlVUclB3Tk9XUDZRV2ZOcEdyUVJGYStCeTNkaEdlS0NTek1ESEJuQUdkRjlFL0gwS00rb2RrVVFsWTMxU1Y3NVpuZzUrY1JyRllwSmcvN3BQM0hFSkNRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJtUVZCZGdvOUtXK1VydWtaRTdvcFFlbjZDUVVNRld2SER3QkpzQS9YVk50TnVJVE94MUhTWElLdjNpQW5FWWZuTDIyVlVrc3JYN3pxZlpMQzFoWDNCdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc5Mzc1MzMyNzo1MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJTdVpzN1BFWXJGWm1QTUdkM09hZGo0Vk9RdzA2QzlyNW5Wem1hcy96cTRGIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzQ1NTg3NzY5LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUZ6diJ9',
    PREFIXE: process.env.PREFIX || ".",
    OWNER_NAME: process.env.OWNER_NAME || "𝐀𝐧𝐝𝐚𝐥𝐚𝐓𝐡𝐞𝐌𝐫",
    NUMERO_OWNER : process.env.NUMERO_OWNER || "254793753327",              
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "yes",
    AUTO_DOWNLOAD_STATUS: process.env.AUTO_DOWNLOAD_STATUS || 'no',
    BOT : process.env.BOT_NAME || 'BMW_MD',
    URL : process.env.BOT_MENU_LINKS || 'https://freeimage.host/i/3O1bfKx',
    MODE: process.env.PUBLIC_MODE || "yes",
    PM_PERMIT: process.env.PM_PERMIT || 'yes',
    HEROKU_APP_NAME : process.env.HEROKU_APP_NAME,
    HEROKU_APY_KEY : process.env.HEROKU_APY_KEY ,
    WARN_COUNT : process.env.WARN_COUNT || '3' ,
    ETAT : process.env.PRESENCE || '',
    ANTICALL : process.env.ANTICALL || 'no',   
    AUTO_BIO : process.env.AUTO_BIO || 'yes',               
    DP : process.env.STARTING_BOT_MESSAGE || "yes",
    ANTIDELETE1 : process.env.ANTI_DELETE_MESSAGE || 'yes',
    AUTO_REACT : process.env.AUTO_REACT || 'no',
    AUTO_REACT : process.env.AUTO_REACT || 'no',              
    AUTO_REACT_STATUS : process.env.AUTO_REACT_STATUS || 'yes',
    AUTO_READ : process.env.AUTO_READ || 'no',
    DATABASE_URL,
    DATABASE: DATABASE_URL === databasePath
        ? "postgresql://postgres:bKlIqoOUWFIHOAhKxRWQtGfKfhGKgmRX@viaduct.proxy.rlwy.net:47738/railway" : "postgresql://postgres:bKlIqoOUWFIHOAhKxRWQtGfKfhGKgmRX@viaduct.proxy.rlwy.net:47738/railway",
   
};
let fichier = require.resolve(__filename);
fs.watchFile(fichier, () => {
    fs.unwatchFile(fichier);
    console.log(`mise à jour ${__filename}`);
    delete require.cache[fichier];
    require(fichier);
});

